ALTER TABLE customers ADD COLUMN favor_balance INTEGER NOT NULL DEFAULT 0;
ALTER TABLE customers ADD COLUMN return_credit_balance INTEGER NOT NULL DEFAULT 0;
ALTER TABLE customers ADD COLUMN fidelity_balance INTEGER NOT NULL DEFAULT 0;
ALTER TABLE customers ADD COLUMN fidelity_accumulated INTEGER NOT NULL DEFAULT 0;

ALTER TABLE sales ADD COLUMN credit_applied INTEGER NOT NULL DEFAULT 0;
ALTER TABLE sales ADD COLUMN fidelity_applied INTEGER NOT NULL DEFAULT 0;
